from flask import Flask, request, jsonify, render_template

app = Flask(__name__, template_folder='templates')

# A simple dictionary to store your blog post data
blog_posts = {
    'ai-ethics': {
        'title': 'The Ethical Dilemmas of Modern AI',
        'subtitle': 'A look into the moral and societal challenges we face as artificial intelligence becomes more advanced.',
        'image': 'https://placehold.co/1000x500/4285F4/FFFFFF?text=AI+Ethics',
        'image_alt': 'A stylized image representing AI ethics and responsibility',
        'author': 'Jane Doe',
        'date': 'September 10, 2025',
        'content': [
            "Artificial intelligence is no longer a futuristic concept; it is an intrinsic part of our present, shaping everything from our daily recommendations to complex medical diagnoses. As its capabilities grow, so too do the ethical questions surrounding its development and deployment.",
            "One of the most pressing concerns is **algorithmic bias**. AI systems learn from data, and if that data reflects existing societal prejudices—be it racial, gender, or socioeconomic—the AI will not only learn these biases but may also amplify them. This can lead to unfair outcomes in critical areas like loan approvals, hiring decisions, and criminal justice. Ensuring diverse and representative training data is a crucial first step, but it is not a complete solution. We also need transparent auditing processes to regularly check for and mitigate bias.",
            "Another significant dilemma revolves around **privacy and surveillance**. AI systems require vast amounts of data to function effectively. This often involves collecting personal information, sometimes without explicit user consent or a clear understanding of how it will be used. The line between personalized service and intrusive surveillance becomes blurred. For example, AI-powered facial recognition can be a powerful tool for law enforcement, but it also raises serious questions about public surveillance and individual freedoms.",
            "The issue of **accountability** is also a complex puzzle. When an autonomous vehicle causes an accident, who is at fault? Is it the programmer, the company that developed the software, or the user? As AI takes on more decision-making roles, the traditional legal frameworks are struggling to keep up. Establishing clear lines of responsibility is vital for public trust and for the safe integration of these technologies into society.",
            "Finally, we must consider the broader societal impact on **employment**. While AI has the potential to automate mundane tasks and create new, higher-skilled jobs, it also threatens to displace workers in various sectors. The ethical imperative here is to manage this transition responsibly, providing educational resources and social safety nets for those whose livelihoods are affected.",
            "The journey of AI is not just about technological advancement, but about a collective ethical reckoning. We have a responsibility to guide its development in a way that prioritizes fairness, protects privacy, and ensures a more equitable future for everyone."
        ]
    },
    'cybersecurity': {
        'title': '5 Essential Steps to Secure Your Digital Life',
        'subtitle': 'Protecting your online accounts is more important than ever. Here are five simple yet powerful steps you can take today.',
        'image': 'https://placehold.co/600x400/34A853/FFFFFF?text=Cybersecurity',
        'image_alt': 'A stylized image representing cybersecurity with a padlock',
        'author': 'John Smith',
        'date': 'September 5, 2025',
        'content': [
            "With an ever-increasing amount of our personal and professional lives conducted online, the need for robust cybersecurity has never been more critical. Here are five simple, yet powerful, steps you can take right now to secure your digital life.",
            "**1. Use Strong, Unique Passwords and a Password Manager:** The weakest link in digital security is often a reusable or simple password. Ditch '123456' and 'password.' Instead, use a password manager like 1Password or LastPass to generate and store unique, complex passwords for every account. This single step will drastically reduce your risk of a data breach.",
            "**2. Enable Multi-Factor Authentication (MFA):** MFA adds an extra layer of security beyond just a password. Even if a hacker gets your password, they can't log in without the second factor, such as a code sent to your phone or generated by an authenticator app. Most major services like Google, Microsoft, and social media platforms offer this for free.",
            "**3. Be Wary of Phishing Attempts:** Phishing emails and messages are a primary vector for cyberattacks. Always be skeptical of urgent requests for personal information, especially from unfamiliar senders. Check the sender's email address for authenticity and never click on suspicious links or download attachments from unknown sources.",
            "**4. Keep Your Software Updated:** Software updates often contain critical security patches that fix vulnerabilities. Make sure your operating system, web browser, and all applications are set to update automatically. This simple habit can protect you from newly discovered exploits.",
            "**5. Back Up Your Data Regularly:** Ransomware and other forms of malware can encrypt or destroy your files. Having a recent backup of your important data, stored on an external hard drive or in the cloud, ensures that you can recover quickly from an attack without having to pay a ransom."
        ]
    },
    'digital-wellbeing': {
        'title': 'Finding Balance in a Hyper-Connected World',
        'subtitle': 'Constant notifications and endless scrolling can be draining. Learn how to build healthier habits with your devices.',
        'image': 'https://placehold.co/600x400/FBBC05/FFFFFF?text=Digital+Wellbeing',
        'image_alt': 'A stylized image representing digital wellbeing with a balanced scale',
        'author': 'Alex Johnson',
        'date': 'August 28, 2025',
        'content': [
            "In our hyper-connected world, our digital lives are often inseparable from our physical ones. While technology offers incredible convenience and connection, it can also lead to burnout, anxiety, and a feeling of being constantly 'on.' Finding a healthy balance is crucial for our mental and physical well-being.",
            "One effective strategy is to create **intentional 'offline' periods.** Designate specific times each day or week where you disconnect completely. This could be during meals, before bed, or for an hour on the weekend. Use this time to read a physical book, go for a walk, or spend quality time with friends and family without distractions.",
            "Another approach is to **curate your digital environment.** Unsubscribe from newsletters you never read, unfollow social media accounts that make you feel bad, and turn off unnecessary notifications. By decluttering your digital space, you reduce the constant pull of your phone and reclaim control over your attention.",
            "**Mindful tech usage** is also key. Instead of mindlessly scrolling, ask yourself why you're picking up your device. Is it to complete a specific task, or are you simply looking for a distraction? By becoming more aware of your habits, you can make more conscious choices about how and when you use technology.",
            "Finally, remember the importance of **physical connection**. Technology is great for staying in touch, but it's not a substitute for real-world interactions. Make an effort to meet up with friends, join a club, or volunteer. These activities can help ground you and remind you of the richness of life beyond the screen."
        ]
    }
}


# Route to serve the homepage (index.html)
@app.route('/')
def home():
    return render_template('index.html')

# Route to serve the blog page (blog.html)
@app.route('/blog.html')
def blog():
    return render_template('blog.html', articles=blog_posts.values())

# Route to serve a specific article page (e.g., /articles/ai-ethics)
@app.route('/articles/<slug>')
def article(slug):
    article_data = blog_posts.get(slug)
    if not article_data:
        return "Article not found", 404
    return render_template('article.html', article=article_data)

# Route to handle the contact form submission
@app.route('/api/contact', methods=['POST'])
def contact():
    data = request.get_json()
    name = data.get('name')
    email = data.get('email')
    message = data.get('message')
    print(f"Contact form: {name} <{email}>: {message}")
    return jsonify(success=True)

if __name__ == '__main__':
    app.run(debug=True)
